### ISSUE TITLE
Error when converting to minetrack5

### ISSUE THREAD

**Issue by moom0o** [Cryptkeeper/Minetrack#245]
```
/mnt/slab/MOO/Minetrack5/lib/database.js:54
      for (const row of pingData) {
                        ^

TypeError: pingData is not iterable
    at /mnt/slab/MOO/Minetrack5/lib/database.js:54:25
    at Statement.<anonymous> (/mnt/slab/MOO/Minetrack5/lib/database.js:128:21)

```
I've reset the entire database and sucked it up, but I'd like to have the old records.

**Comment by hugmanrique** [comment]
Make sure you're running Node 12.4.0+, you can check with `node -v`.

**Comment by moom0o** [comment]
v14.15.5

**Comment by hugmanrique** [comment]
Can you give the PR above a go and see if it logs the real cause for the error?

**Comment by moom0o** [comment]
9:58:44 PM 4/21/2021 - error: Cannot get recent pings
undefined:0



[Error: SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}

Something did happen with the disk before this, is there an easy way to repair the SQL database?

**Comment by hugmanrique** [comment]
Your database file is corrupt. Try (re)moving the `database.sql` file in Minetrack's root directory. The `sqlite` program may [be able to recover the data](https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database/57872238#57872238).

**Comment by Cryptkeeper** [comment]
Closing due to inactivity.
