### ISSUE TITLE
Error whilst building

### ISSUE THREAD

**Issue by JanCantCode** [Cryptkeeper/Minetrack#373]
Whilst running npm run build after npm install on my raspberry pi, i encounter the following error:

```🚨 Build failed.

@parcel/transformer-css: Could not resolve module "/home/pi/statistics/Minetrack/node_modules/lightningcss/lightningcss.linux-arm64-gnu.node" from
"/home/pi/statistics/Minetrack/node_modules/lightningcss/node/index.js"

  Error: Could not resolve module "/home/pi/statistics/Minetrack/node_modules/lightningcss/lightningcss.linux-arm64-gnu.node" from "/home/pi/statistics/Minetrack/node_modules/lightningcss/node/index.js"
      at $0578d0f6e116167e$export$fb2a0b866a8162dc.resolve (/home/pi/statistics/Minetrack/node_modules/@parcel/package-manager/lib/index.js:4991:21)
      at NodePackageManager.resolveSync (/home/pi/statistics/Minetrack/node_modules/@parcel/package-manager/lib/index.js:3510:42)
      at NodePackageManager.requireSync (/home/pi/statistics/Minetrack/node_modules/@parcel/package-manager/lib/index.js:3352:34)
      at Module.m.require (/home/pi/statistics/Minetrack/node_modules/@parcel/package-manager/lib/index.js:3366:25)
      at require (/home/pi/statistics/Minetrack/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
      at Object.<anonymous> (/home/pi/statistics/Minetrack/node_modules/lightningcss/node/index.js:21:22)
      at Module._compile (/home/pi/statistics/Minetrack/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at NodePackageManager.load (/home/pi/statistics/Minetrack/node_modules/@parcel/package-manager/lib/index.js:3375:15)

npm ERR! code 1
npm ERR! path /home/pi/statistics/Minetrack
npm ERR! command failed
npm ERR! command sh -c eslint assets/js/*.js && parcel build assets/html/index.html --dist-dir dist```. Because stuff isnt bundled now, i cant access the webview.. any fix?

**Comment by Euro-pol** [comment]
I'm having this error too. Did you find a way to fix it?

**Comment by JanCantCode** [comment]
> I'm having this error too. Did you find a way to fix it?

i just cloned it on my windows device, ran the build script that bundled the ressources, and uploaded the bundled ressource folder to a server and downloaded it with my raspberry pi - that worked

**Comment by Euro-pol** [comment]
> > I'm having this error too. Did you find a way to fix it?
> 
> i just cloned it on my windows device, ran the build script that bundled the ressources, and uploaded the bundled ressource folder to a server and downloaded it with my raspberry pi - that worked

Thanks!
