### ISSUE TITLE
Error whilst building 

### ISSUE THREAD

**Issue by vubaolinh123** [Cryptkeeper/Minetrack#388]
Whilst running npm run build after npm install, i encounter the following error:

 minetrack@5.6.1 build
 eslint assets/js/*.js && parcel build assets/html/index.html --dist-dir dist

console: (node:5276) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 25 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to× Build failed.
@parcel/optimizer-terser: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\terser\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\terser\node_modules\source-map\lib\wasm.js:25:16)
    at C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\terser\node_modules\source-map\lib\source-map-consumer.js:264:14
    at async SourceMap (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\terser\dist\bundle.min.js:18236:20)
    at async minify (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\terser\dist\bundle.min.js:26555:41)
    at async Object.optimize (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\@parcel\optimizer-terser\lib\TerserOptimizer.js:114:16)
    at async PackagerRunner.optimize (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\@parcel\core\lib\PackagerRunner.js:427:20)
    at async PackagerRunner.getBundleResult (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\@parcel\core\lib\PackagerRunner.js:328:15)
    at async PackagerRunner.getBundleInfo (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\@parcel\core\lib\PackagerRunner.js:318:9)
    at async Child.handleRequest (C:\Users\Admin\Desktop\Minetrack-5.6.1\Minetrack-5.6.1\node_modules\@parcel\workers\lib\child.js:255:9)

**Comment by Ryneit** [comment]
i have the same error but idk how to solve

**Comment by Bansku-Dansku** [comment]
Its probably some of the packages that are messing up.
