### ISSUE TITLE
Allow the "port": "xxxxx" + other issue

### ISSUE THREAD

**Issue by TNTUP** [Cryptkeeper/Minetrack#45]
Hi, I've looked in the closed issues and I found what I want, but I tried it in the servers.json and it doesn't work if I specify the port manually. It says ECONREFUSED though the server is online (1.8.8).

I've seen in the code it supports SRV domains, I've setup one so it will accept it but there's a server which I added and it keeps crashing. Saying something out of range.

I tried adding bbc.mcqc.ca (SRV) and it crashes. With its original IP it still crashes.

buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
          ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt8 (buffer.js:588:5)
    at CustomBuffer.readVarInt (/home/admin/Minetrack/node_modules/mc-ping-updated/lib/mcpc_buffer.js:49:28)
    at Socket.<anonymous> (/home/admin/Minetrack/node_modules/mc-ping-updated/lib/ping.js:77:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)

Now it keeps crashing everytime if I re-add this server in the config. everything works as normal. 

That server is on 1.8.8, others are on 1.9/1.10.

**Comment by ThorinDev** [comment]
I have tested this on my own machine and I think I know where you could be going wrong.  
If you are doing this in your servers.json file
```
"port" : "12345"
```
you are specifying the port as a string which **WILL NOT** work  
you need to do this
```
"port": 12345
```
that way works fine on my machine.

**Comment by TNTUP** [comment]
Oooh nice tip, didn't know that, in JSON I don't even know it carefully xD Thanks :D
